### ISSUE TITLE
функції, що повертають boolean

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/js-functions#1]
https://github.com/DenisPitsul/js-functions/blob/93bdc0357b4e252ca49a27516e65310d1d6f9132/assets/js/task2.js#L7
- зазвичай не пишуть: "якщо істина, то повернути істину, інакше повернути хибу". Порівняння і так поверне логічне значення, от його можна одразу і повертати:
```javascript
  if (secondNumber === 0) {
    return false;
  }

  return firstNumber % secondNumber === 0;
``` 
або навіть так:
```javascript
  return !(secondNumber === 0) && firstNumber % secondNumber === 0;
```

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/js-functions/commit/3d7ec1f346b06f3bb0013e9c1162202c41a425a2
